spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vocabulary_db
    username: vocabulary_user
    password: vocabulary_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Zipkin Configuration for Distributed Tracing (local Docker container)
spring.zipkin:
  base-url: http://localhost:9411
  enabled: true

# Logging Configuration for local development
logging:
  level:
    root: INFO
    me.maximilianmilz.vocabulary: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
